### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by TysonMN**
Changes:
"with" to "we"
"use" to "used"
added "have"

> `cm` and `gm` are the SI units for volume and mass.

Isn't `mg` the abbreviation for milllgrams?  There are many occurances of `gm` in your post.

### CODE REVIEW

**Comment by TysonMN** [comment]
Are these HTML files generated or do you write them yourself?

**Comment by TysonMN** [comment]
Oh, I think this PR is for the wrong file.  The file edited in this PR is nearly identical to [this file](https://github.com/matthewcrews/matthewcrews.github.io/blob/main/blog/2020/12/2020-12-14/index.html).

**Comment by TysonMN** [comment]
Replaced by PR #3

**Comment by matthewcrews** [comment]
FYI, this is the repo that holds the site that is hosted. The repo where I actually write the posts and generate this site using Hugo is here:
https://github.com/matthewcrews/blog

That's the place to make edits. Thanks for the help!

**Pull request closed without merging**
